const KEY='harmonic-city-state-v1',MEDIA='harmonic-city-media-v1';
const defaults={portalTitle:'Harmonic City',heroTitle:'Harmonic City',heroEyebrow:'WELCOME TO YOUR UNIVERSE',heroDescription:'Hoopz, food, fashion, and every world connected to Melodic. Choose your melody.',introTitle:'Harmonic City',introKicker:'WELCOME TO',headlineFont:'Archivo Black',bodyFont:'Inter',iconScale:100,orbitSpeed:26,volume:.7,primary:'#d8b67a',secondary:'#8e6840',accent:'#f7e7bd',background:'#0b0806',surface:'#1a120d',text:'#fff8e9',activeWorld:'thatsmelodic',backgroundMediaId:null,introMediaId:null,audioMediaId:null,worlds:[{id:'thatsmelodic',name:'thatsmelodic',eyebrow:'PERSONAL PAGE / MAIN HUB',description:'Music, personality, basketball, behind-the-scenes content, announcements, and the bridge connecting every brand.',emoji:'🎵',socials:{youtube:'https://www.youtube.com/@thatsmelodic',instagram:'https://www.instagram.com/thatsmelodic',tiktok:'https://www.tiktok.com/@thatsmelodic',facebook:'https://www.facebook.com/share/1G8drmZJ7s/'}},{id:'schmakinn',name:'Schmakinn',eyebrow:'EATING CHANNEL',description:'Food reviews, mukbangs, challenges, honest reactions, and meals that are actually schmackin.',emoji:'🍔',socials:{youtube:'https://youtube.com/@schmackinn',instagram:'https://www.instagram.com/schmakinn',tiktok:'https://www.tiktok.com/@schmackinn',facebook:'https://www.facebook.com/share/1H9x4fD9zo/'}},{id:'2harmonic',name:'2Harmonic',eyebrow:'CLOTHING LINE',description:'Stitched Melodies—fashion built around harmony, expression, duality, and the messages that keep people moving.',emoji:'👕',socials:{youtube:'https://youtube.com/@2harmonic',instagram:'https://www.instagram.com/2harmonic',facebook:'https://www.facebook.com/share/183jemgJ89/',website:'https://twoharmonic.com'}}]};
const themes={lifted:{label:'Lifted Beige',primary:'#d8b67a',secondary:'#8e6840',accent:'#f7e7bd',background:'#0b0806',surface:'#1a120d',text:'#fff8e9',headlineFont:'Playfair Display'},royal:{label:'Royal Desert',primary:'#c89b57',secondary:'#6d4827',accent:'#fff0c7',background:'#100b07',surface:'#25170e',text:'#fff9ec',headlineFont:'Playfair Display'},midnight:{label:'Midnight Melody',primary:'#a54cff',secondary:'#5520a8',accent:'#ff57dc',background:'#06020a',surface:'#160920',text:'#fbf5ff',headlineFont:'Archivo Black'},food:{label:'Schmakinn Neon',primary:'#ff5a24',secondary:'#1588ff',accent:'#72ff49',background:'#070707',surface:'#1c100a',text:'#fff5e9',headlineFont:'Archivo Black'},gym:{label:'Fried Em Gym',primary:'#8a52ff',secondary:'#e03737',accent:'#fff',background:'#08070c',surface:'#17121f',text:'#fff',headlineFont:'Archivo Black'},rose:{label:'Rose Gold',primary:'#d9939f',secondary:'#805461',accent:'#ffe8df',background:'#10080b',surface:'#25151b',text:'#fff7f3',headlineFont:'Playfair Display'}};
const load=(k,f)=>{try{return Object.assign(structuredClone(f),JSON.parse(localStorage.getItem(k))||{})}catch{return structuredClone(f)}};
let state=load(KEY,defaults),library=load(MEDIA,{background:[],intro:[],audio:[]}),audio=new Audio(),playing=false,timer;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){clearTimeout(timer);$('#saveStatus').textContent='Saving…';timer=setTimeout(()=>{localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(MEDIA,JSON.stringify(library));$('#saveStatus').textContent='Saved automatically';},250)}
function media(kind,id){return library[kind].find(x=>x.id===id)}
function element(item){const e=document.createElement(item.type.startsWith('video/')?'video':'img');e.src=item.data;if(e.tagName==='VIDEO'){e.autoplay=e.loop=e.muted=e.playsInline=true}else e.alt='';return e}
function render(){const r=document.documentElement;['primary','secondary','accent','background','surface','text'].forEach(k=>r.style.setProperty('--'+k,state[k]));r.style.setProperty('--icon-scale',state.iconScale/100);r.style.setProperty('--orbit-duration',state.orbitSpeed+'s');r.style.setProperty('--headline',`'${state.headlineFont}'`);r.style.setProperty('--body',`'${state.bodyFont}'`);$('#portalTitleTop').textContent=state.portalTitle.toUpperCase();$('#heroTitle').textContent=state.heroTitle;$('#heroEyebrow').textContent=state.heroEyebrow;$('#heroDescription').textContent=state.heroDescription;$('#introTitle').textContent=state.introTitle;$('#introKicker').textContent=state.introKicker;$$('[data-setting]').forEach(i=>{if(document.activeElement!==i)i.value=state[i.dataset.setting]});audio.volume=state.volume;renderMedia();renderOrbit();renderProfile();renderHistory();renderWorldEditor()}
function renderMedia(){[['background','#backgroundStage'],['intro','#introMedia']].forEach(([k,s])=>{const box=$(s),item=media(k,state[k+'MediaId']);box.innerHTML='';if(item)box.appendChild(element(item))})}
function renderOrbit(){const box=$('#orbitSystem');box.innerHTML='<div class="orbit-ring"></div><div class="orbit-core"></div>';state.worlds.forEach((w,i)=>{const b=document.createElement('button');b.className='world-node';b.style.setProperty('--i',i);b.innerHTML=`<span class="world-icon">${w.customIcon?`<img src="${w.customIcon}">`:w.emoji}</span><span class="world-label">${w.name}</span>`;b.onclick=()=>{state.activeWorld=w.id;renderProfile();save();$('#profileStage').scrollIntoView({behavior:'smooth'})};box.appendChild(b)})}
function renderProfile(){const w=state.worlds.find(x=>x.id===state.activeWorld)||state.worlds[0],f=$('#profileTemplate').content.cloneNode(true);f.querySelector('.profile-art').innerHTML=w.customIcon?`<img src="${w.customIcon}" style="max-width:70%;max-height:70%">`:w.emoji;f.querySelector('.profile-eyebrow').textContent=w.eyebrow;f.querySelector('.profile-title').textContent=w.name;f.querySelector('.profile-description').textContent=w.description;const grid=f.querySelector('.social-grid');Object.entries(w.socials).forEach(([k,u])=>{if(!u)return;const a=document.createElement('a');a.className='social-link';a.href=u;a.target='_blank';a.textContent=k;grid.appendChild(a)});$('#profileStage').replaceChildren(f)}
function setupDrop(zoneSel,inputSel,kind){const z=$(zoneSel),i=$(inputSel);z.onclick=()=>i.click();['dragenter','dragover'].forEach(t=>z.addEventListener(t,e=>{e.preventDefault();z.classList.add('dragover')}));['dragleave','drop'].forEach(t=>z.addEventListener(t,e=>{e.preventDefault();z.classList.remove('dragover')}));z.addEventListener('drop',e=>readFiles(e.dataTransfer.files,kind));i.onchange=e=>readFiles(e.target.files,kind)}
function readFiles(files,kind){[...files].forEach(file=>{const valid=kind==='audio'?file.type.startsWith('audio/'):file.type.startsWith('image/')||file.type.startsWith('video/');if(!valid)return;const r=new FileReader();r.onload=()=>{const item={id:crypto.randomUUID(),name:file.name,type:file.type,data:r.result};library[kind].unshift(item);state[kind+'MediaId']=item.id;if(kind==='audio')loadAudio();render();save()};r.readAsDataURL(file)})}
function renderHistory(){['background','intro','audio'].forEach(kind=>{const box=$('#'+kind+'History');box.innerHTML='';library[kind].forEach(item=>{const c=document.createElement('div');c.className='history-item';if(kind==='audio')c.innerHTML='<div style="display:grid;place-items:center;height:100%;font-size:1.6rem">♪</div>';else c.appendChild(element(item));const x=document.createElement('button');x.textContent='×';x.onclick=e=>{e.stopPropagation();library[kind]=library[kind].filter(m=>m.id!==item.id);if(state[kind+'MediaId']===item.id)state[kind+'MediaId']=null;render();save()};c.appendChild(x);c.onclick=()=>{state[kind+'MediaId']=item.id;if(kind==='audio')loadAudio();render();save()};box.appendChild(c)})})}
function loadAudio(){const item=media('audio',state.audioMediaId);if(!item)return;const was=playing;audio.pause();audio=new Audio(item.data);audio.loop=true;audio.volume=state.volume;audio.onplay=()=>audioUI(true);audio.onpause=()=>audioUI(false);if(was)audio.play()}
function audioUI(on){playing=on;$('#audioToggle').textContent=on?'Ⅱ Pause audio':'▶ Play audio'}
async function toggleAudio(){if(!audio.src)loadAudio();if(!audio.src){$('#audioToggle').textContent='Upload audio first';return}playing?audio.pause():await audio.play().catch(()=>$('#audioToggle').textContent='Tap again to play')}
function renderWorldEditor(){const e=$('#worldEditor');e.innerHTML='';state.worlds.forEach((w,n)=>{const d=document.createElement('details');d.innerHTML=`<summary style="cursor:pointer;font-weight:900;padding:10px 0">${w.name}</summary>`;[['name','World name'],['eyebrow','Label'],['description','Description'],['emoji','Fallback icon']].forEach(([k,l])=>{const label=document.createElement('label'),input=k==='description'?document.createElement('textarea'):document.createElement('input');label.textContent=l;input.value=w[k];input.oninput=()=>{state.worlds[n][k]=input.value;renderOrbit();renderProfile();save()};label.appendChild(input);d.appendChild(label)});const label=document.createElement('label'),input=document.createElement('input');label.textContent='Custom icon';input.type='file';input.accept='image/*';input.onchange=()=>{const f=input.files[0],r=new FileReader();r.onload=()=>{state.worlds[n].customIcon=r.result;render();save()};r.readAsDataURL(f)};label.appendChild(input);d.appendChild(label);e.appendChild(d)})}
Object.entries(themes).forEach(([id,t])=>{const b=document.createElement('button');b.className='theme-button';b.textContent=t.label;b.onclick=()=>{Object.assign(state,t);render();save()};$('#themeGrid').appendChild(b)});
$$('[data-setting]').forEach(i=>i.oninput=()=>{state[i.dataset.setting]=i.type==='range'?Number(i.value):i.value;render();save()});$('#openCustomizer').onclick=()=>$('#customizer').classList.add('open');$('#closeCustomizer').onclick=()=>$('#customizer').classList.remove('open');$('#enterPortal').onclick=()=>$('#introScreen').classList.add('hidden');$('#audioToggle').onclick=toggleAudio;setupDrop('#backgroundDrop','#backgroundInput','background');setupDrop('#introDrop','#introInput','intro');setupDrop('#audioDrop','#audioInput','audio');render();if(state.audioMediaId)loadAudio();
