(() => {
  const LAYOUT_KEY='harmonic-city-studio-layout-v1';
  const STATE_KEY='harmonic-city-state-v2';
  const $=s=>document.querySelector(s);
  const panel=$('#studioPanel'),toggle=$('#studioToggle'),close=$('#studioClose');
  if(!panel||!toggle)return;
  const fields={x:$('#studioX'),y:$('#studioY'),w:$('#studioW'),h:$('#studioH'),rotate:$('#studioRotate'),opacity:$('#studioOpacity')};
  const nameEl=$('#studioSelectionName'),saveEl=$('#studioSaveState');
  const guideV=document.createElement('div'),guideH=document.createElement('div');guideV.className='studio-guide v';guideH.className='studio-guide h';document.body.append(guideV,guideH);
  let active=false,selected=null,mode=null,start=null,undo=[],redo=[],mutationLock=false;
  const defaults={};
  const read=()=>{try{return JSON.parse(localStorage.getItem(LAYOUT_KEY)||'{}')}catch{return{}}};
  let layout=read();
  const write=()=>{localStorage.setItem(LAYOUT_KEY,JSON.stringify(layout));saveEl.textContent='Layout saved automatically';setTimeout(()=>saveEl.textContent='Layout autosaves.',900)};
  const idOf=el=>el?.dataset?.studioId||el?.id||null;
  const eligible=()=>[...document.querySelectorAll('[data-studio-id],.profile-art,.profile-info')];
  function decorate(){eligible().forEach(el=>{if(!el.dataset.studioId){if(el.classList.contains('profile-art'))el.dataset.studioId='profile-art';if(el.classList.contains('profile-info'))el.dataset.studioId='profile-info'};const id=idOf(el);if(id&&!defaults[id])defaults[id]={css:el.getAttribute('style')||''};applyOne(el)});document.querySelectorAll('#heroEyebrow,#heroTitle,#heroDescription,.profile-eyebrow,.profile-title,.profile-description').forEach(el=>{el.classList.add('studio-editable-text');if(!el.dataset.studioText){if(el.classList.contains('profile-eyebrow'))el.dataset.studioText='worldEyebrow';if(el.classList.contains('profile-title'))el.dataset.studioText='worldName';if(el.classList.contains('profile-description'))el.dataset.studioText='worldDescription'}})}
  function applyOne(el){const id=idOf(el),v=layout[id];if(!id||!v)return;el.style.translate=`${v.x||0}px ${v.y||0}px`;el.style.width=v.w?`${v.w}px`:'';el.style.height=v.h?`${v.h}px`:'';el.style.rotate=`${v.rotate||0}deg`;el.style.opacity=v.opacity??1}
  function snapshot(){undo.push(JSON.stringify(layout));if(undo.length>50)undo.shift();redo=[]}
  function select(el){selected?.classList.remove('studio-selected');selected=el;if(!el){nameEl.textContent='Nothing selected';return}el.classList.add('studio-selected');const r=el.getBoundingClientRect(),id=idOf(el),v=layout[id]||{};nameEl.textContent=id.replaceAll('-',' ');fields.x.value=Math.round(v.x||0);fields.y.value=Math.round(v.y||0);fields.w.value=Math.round(v.w||r.width);fields.h.value=Math.round(v.h||r.height);fields.rotate.value=v.rotate||0;fields.opacity.value=v.opacity??1}
  function setValue(key,value){if(!selected)return;const id=idOf(selected);snapshot();layout[id]={...(layout[id]||{}),[key]:Number(value)};applyOne(selected);write();select(selected)}
  Object.entries(fields).forEach(([k,input])=>input?.addEventListener('change',()=>setValue(k,input.value)));
  function begin(e,resize=false){if(!active)return;const target=e.target.closest('[data-studio-id],.profile-art,.profile-info');if(!target)return;e.preventDefault();select(target);snapshot();const r=target.getBoundingClientRect(),id=idOf(target),v=layout[id]||{};mode=resize?'resize':'drag';start={px:e.clientX,py:e.clientY,x:v.x||0,y:v.y||0,w:v.w||r.width,h:v.h||r.height,id};target.setPointerCapture?.(e.pointerId)}
  document.addEventListener('pointerdown',e=>{if(!active)return;const target=e.target.closest('[data-studio-id],.profile-art,.profile-info');if(!target)return;const r=target.getBoundingClientRect();const resize=e.clientX>r.right-22&&e.clientY>r.bottom-22;begin(e,resize)});
  document.addEventListener('pointermove',e=>{if(!mode||!selected)return;const dx=e.clientX-start.px,dy=e.clientY-start.py;let v={...(layout[start.id]||{})};if(mode==='drag'){v.x=start.x+dx;v.y=start.y+dy;const rr=selected.getBoundingClientRect(),cx=rr.left+rr.width/2,cy=rr.top+rr.height/2;const snapX=Math.abs(cx-innerWidth/2)<9,snapY=Math.abs(cy-innerHeight/2)<9;guideV.style.display=snapX?'block':'none';guideH.style.display=snapY?'block':'none';guideV.style.left='50%';guideH.style.top='50%';if(snapX)v.x+=innerWidth/2-cx;if(snapY)v.y+=innerHeight/2-cy}else{v.w=Math.max(40,start.w+dx);v.h=Math.max(40,start.h+dy)}layout[start.id]=v;applyOne(selected);select(selected)});
  document.addEventListener('pointerup',()=>{if(mode){mode=null;guideV.style.display=guideH.style.display='none';write()}});
  function syncText(el){const key=el.dataset.studioText;if(!key)return;let state={};try{state=JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{};const text=el.textContent.trim();if(key==='heroTitle'||key==='heroEyebrow'||key==='heroDescription'){state[key]=text}else{const activeId=state.activeWorld||'thatsmelodic';const worlds=state.worlds||[];const w=worlds.find(x=>x.id===activeId);if(w){if(key==='worldName')w.name=text;if(key==='worldEyebrow')w.eyebrow=text;if(key==='worldDescription')w.description=text}}localStorage.setItem(STATE_KEY,JSON.stringify(state));document.querySelector(`[data-setting="${key}"]`)?.setAttribute('value',text)}
  document.addEventListener('dblclick',e=>{if(!active)return;const el=e.target.closest('[data-studio-text],.profile-eyebrow,.profile-title,.profile-description');if(!el)return;e.preventDefault();el.contentEditable='true';el.focus();const range=document.createRange();range.selectNodeContents(el);const sel=getSelection();sel.removeAllRanges();sel.addRange(range)});
  document.addEventListener('focusout',e=>{const el=e.target.closest?.('[contenteditable="true"]');if(!el)return;el.contentEditable='false';syncText(el)});
  function restore(serialized,targetStack){targetStack.push(JSON.stringify(layout));layout=JSON.parse(serialized||'{}');eligible().forEach(applyOne);write();select(selected)}
  $('#studioUndo')?.addEventListener('click',()=>{if(!undo.length)return;restore(undo.pop(),redo)});$('#studioRedo')?.addEventListener('click',()=>{if(!redo.length)return;restore(redo.pop(),undo)});
  $('#studioReset')?.addEventListener('click',()=>{snapshot();if(selected){const id=idOf(selected);delete layout[id];selected.removeAttribute('style');select(selected)}else{layout={};eligible().forEach(el=>el.removeAttribute('style'))}write()});
  document.querySelectorAll('[data-align]').forEach(btn=>btn.addEventListener('click',()=>{if(!selected)return;const parent=selected.offsetParent||selected.parentElement,pr=parent.getBoundingClientRect(),r=selected.getBoundingClientRect(),id=idOf(selected),v={...(layout[id]||{})};snapshot();if(btn.dataset.align==='left')v.x+=(pr.left-r.left);if(btn.dataset.align==='right')v.x+=(pr.right-r.right);if(btn.dataset.align==='center')v.x+=(pr.left+pr.width/2-(r.left+r.width/2));if(btn.dataset.align==='top')v.y+=(pr.top-r.top);if(btn.dataset.align==='bottom')v.y+=(pr.bottom-r.bottom);if(btn.dataset.align==='middle')v.y+=(pr.top+pr.height/2-(r.top+r.height/2));layout[id]=v;applyOne(selected);write();select(selected)}));
  function setActive(on){active=on;document.body.classList.toggle('studio-editing',on);panel.classList.toggle('open',on);toggle.classList.toggle('active',on);toggle.textContent=on?'✓ Editing':'✦ Edit';panel.setAttribute('aria-hidden',String(!on));if(!on)select(null);else decorate()}
  toggle.addEventListener('click',()=>setActive(!active));close?.addEventListener('click',()=>setActive(false));
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?$('#studioRedo')?.click():$('#studioUndo')?.click()}if(e.key==='Escape'&&active)setActive(false)});
  const observer=new MutationObserver(()=>{if(mutationLock)return;mutationLock=true;requestAnimationFrame(()=>{decorate();mutationLock=false})});observer.observe($('#portal'),{childList:true,subtree:true});
  decorate();
})();